spring:
  application:
    name: cashtracker
  datasource:
    url: jdbc:sqlite:${user.home}/.cashtracker/cashtracker.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: none
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8090
